# Generated by Django 4.1.2 on 2022-10-28 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='newstats',
            new_name='OperatingSystemStats',
        ),
    ]
